project:
  render: 
    - bkm_ch_01.qmd
    - bkm_ch_02.qmd
    - bkm_ch_03.qmd
    - bkm_ch_04.qmd
    - bkm_ch_05.qmd
    - bkm_ch_06.qmd
    - bkm_ch_07.qmd
    - bkm_ch_09.qmd
    - bkm_ch_10.qmd
    - bkm_ch_11.qmd
    - bkm_ch_12.qmd
    - bkm_ch_13.qmd
    - bkm_ch_14.qmd
    - bkm_ch_15.qmd
    - bkm_ch_24.qmd

format:
  beamer:
    cite-method: biblatex
    biblio-style: authoryear
    biblio-title: References
    section-titles: false
    slide-level: 3
    innertheme: circles
    aspectratio: 169