author: Richard Herron
institute: D'Amore-McKim School of Business, Northeastern University
bibliography: references.bib
cite-method: biblatex
biblio-style: authoryear
biblio-title: References

profile:
  group: 
    - [book, slides]
